### ISSUE TITLE
run call.consensus..py  fail

### ISSUE THREAD

**Issue by lstxmu** [kishwarshafin/helen#11] opened 2019-07-19 13:50 UTC
i can't run 'python3 cal_consensus.py',  and i got the follow message "  Traceback (most recent call last):
  File "./call_consensus.py", line 3, in <module>
    from modules.python.TextColor import TextColor
ImportError: No module named 'modules.python'
"
any guy can help me ?

**Comment by kishwarshafin** [comment] 2019-07-19 14:05
Hello. This may be because of the relative path. Can you please make sure that you are running the script from inside the helen directory and when you run `ls` or `ll` in the directory you are running the command from, you can see the `modules` directory in the list?

**Comment by lstxmu** [comment] 2019-07-19 17:54
hi,kishwarshafin . 
according your suggestion, i ran  the script inside the helen directory again,  unfortunately, the error message still happen.
you can see my record :
$ python3 /opt/biosoft/bioinfo/Helen/call_consensus.py -h
Traceback (most recent call last):
  File "/opt/biosoft/bioinfo/Helen/call_consensus.py", line 3, in <module>
    from modules.python.TextColor import TextColor
ImportError: No module named 'modules.python'

![Selection_073](https://user-images.githubusercontent.com/46129804/61555051-05745280-aa91-11e9-9c7f-2aab1b87be0c.png)

please help me fix this issue,, thanks a lot.

**Comment by kishwarshafin** [comment] 2019-07-19 18:01
@lstxmu , can you please run `pwd` to see your present working directory? 

also, can you please try simply running `python3 call_consensus.py -h` instead of giving the full path?  I am not sure if setting the absolute path for the python script is causing this.

**Comment by lstxmu** [comment] 2019-07-19 18:13
@kishwarshafin  , i simply run  " python3 call_consensus.py -h" , but still fail agagin. 
but when i try  run "./cal_consensus.py -h" ,   i  work , with some error  message.    
![Selection_074](https://user-images.githubusercontent.com/46129804/61556216-e7f4b800-aa93-11e9-8562-a3ead18fbb47.png)
you can see the record.   why the issue happen?

**Comment by kishwarshafin** [comment] 2019-07-19 18:22
I would try to re-generate this somewhere. Can you please tell me about your OS and python3 version? 

I would need the outputs of `lsb_release -a` and `python3 --version`. Thanks.

**Comment by lstxmu** [comment] 2019-07-19 18:28
@kishwarshafin 
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
$ python3 --version
Python 3.5.3

thanks a lot!

**Comment by kishwarshafin** [comment] 2019-07-19 19:08
hello @lstxmu , I just created a google-cloud-instance with your config. 

This is my instance's setup:
```
kishwar@helen-test:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

```
kishwar@helen-test:~$ python3 --version
Python 3.5.3
```

1) Then install python and all:
```
sudo apt-get -y install python3 python3-dev python3-pip
```

The python version was still the same:
```
kishwar@helen-test:~/helen$ python3 --version
Python 3.5.3
```

Then I installed torch and torchvision for linux from https://pytorch.org/

Then install all the other tools
```
python3 -m pip install h5py tqdm numpy torchnet pyyaml
```

If I run these commands to see if HELEN works:
```
sudo apt-get install git
git clone https://github.com/kishwarshafin/helen.git
cd helen/
python3 call_consensus.py
```

I get this output:
```
kishwar@helen-test:~/helen$ python3 call_consensus.py
usage: call_consensus.py [-h] -i IMAGE_FILE -m MODEL_PATH [-b BATCH_SIZE]
                         [-w NUM_WORKERS] [-t THREADS] [-o OUTPUT_DIR] [-g]
call_consensus.py: error: the following arguments are required: -i/--image_file, -m/--model_path
```

Are you sure you are following the instructions correctly?

**Comment by kishwarshafin** [comment] 2019-07-19 19:23
@lstxmu from your `ll` output I see all the files are executable. Did you do `chmod` on the files? If yes, can you do `cd modules` and then `ll` to see if the subdirectories are there?

**Comment by lstxmu** [comment] 2019-07-20 14:24
@kishwarshafin 
i had follow your intruduction step by step,  delete the old helen direcotry , install  every dependency software you had decribed above.  But i still get the wrong message, the call_consensus.py not work.
![Selection_081](https://user-images.githubusercontent.com/46129804/61579836-f945cf00-ab3c-11e9-95b5-bea2b3691123.png)
![Selection_082](https://user-images.githubusercontent.com/46129804/61579843-05ca2780-ab3d-11e9-8f9e-e070499b3af8.png)

i think i cant fix it , it's so bad.

**Comment by kishwarshafin** [comment] 2019-07-20 14:45
@lstxmu, I am sorry this is happening. Are you using any shell program like `fish`? Importing from subdirectories is a very standard python practice, not sure why it is failing. Do you have any other Ubuntu/Linux based system where you can try it quickly?

**Comment by lstxmu** [comment] 2019-07-20 15:07
@kishwarshafin   I  had try it using the zsh and bash,   and it happened in both shell program.  i cant find what the 'module.python' means in google.   I will try it  again in ubuntu or centos these days,  and i will tell you the result.
I sincerely thank you all.

**Comment by kishwarshafin** [comment] 2019-07-20 15:09
@lstxmu , the modules.python is the `modules` subdirectory you have inside helen directory and `python` is the subdirectory inside `modules`. I am trying to recreate this issue locally. If I can, I'll get back to you.

**Comment by kishwarshafin** [comment] 2019-07-21 04:14
Hi @lstxmu , I have uploaded two docker images to get around this problem today. If you are going to use GPUs then run this:
```
sudo apt-get install nvidia-docker2
sudo docker pull kishwars/helen:0.0.1.gpu

# change -v parameter to the directory where your data live
sudo nvidia-docker run -v /data:/data kishwars/helen:0.0.1.gpu call_consensus.py \
-i </data/marginpolish_images> \
-b 1024 \
-m </data/models/r941_flip235_v001.pkl> \
-o </data/output_dir/> \
-w 0 \
-t 1 \
-g
```

If you are using CPUs:
```
sudo docker pull kishwars/helen:0.0.1.cpu

# change -v parameter to the directory where your data live
sudo docker run -v /data:/data  kishwars/helen:0.0.1.cpu call_consensus.py \
-i </data/marginpolish_images> \
-b 1024 \
-m </data/models/r941_flip235_v001.pkl> \
-o </data/output_dir/> \
-w 16 \
-t 1
```

Please let me know if this works for you.

**Comment by lstxmu** [comment] 2019-07-22 09:19
@kishwarshafin  hi,kishwarshafin. it seem the docker version you had provided works.  But i'm not good at docker operation. I will take  some time to see what would happen next  , please wait my message.
thanks for your help.

![Selection_086](https://user-images.githubusercontent.com/46129804/61621176-f8c84800-aca4-11e9-9063-a41fd62223d0.png)

**Comment by lstxmu** [comment] 2019-07-22 10:18
@kishwarshafin   I'm sorry to tell that docker version still faiil.  The output message as follow: 
![result](https://user-images.githubusercontent.com/46129804/61625365-1ef1e600-acad-11e9-9067-1a4b923f71ec.png)

**Comment by kishwarshafin** [comment] 2019-07-22 15:01
@lstxmu , this is expected output. The program can not find the model file. You have to mount your volume where all the inputs are to "/data" using the -v parameter and then point the inputs correctly from directories where they exist. Please read here:

https://docs.docker.com/v17.12/engine/reference/commandline/run/

**Comment by lstxmu** [comment] 2019-07-23 15:39
@kishwarshafin   hi.kishwarshafin . i had try your suggestion. but i dont think it can run susscesfully.  the progress of python was suspend and nothing change  after miniutes. 
![Selection_095](https://user-images.githubusercontent.com/46129804/61725791-0532ca80-ada3-11e9-9455-dae04e1d6f4c.png)

may be i should gave up trying. 
thanks for your help

**Comment by kishwarshafin** [comment] 2019-07-23 15:47
@lstxmu , how many CPU cores do you have? I don't see any reason for this to fail.

**Comment by lstxmu** [comment] 2019-07-23 15:48
@kishwarshafin   sudo docker run -v /media/datarun2/helendata:/media/datarun2/helendata  kishwars/helen:0.0.1.cpu  call_consensus.py \ 
-i  /media/datarun2/helendata/images -b 1024 -m /media/datarun2/helendata/models/r941_flip235_v001.pkl -o /media/datarun2/helendata/out -w 16 -t 144

**Comment by kishwarshafin** [comment] 2019-07-23 15:49
What is the output of `nproc --all` for you?

**Comment by kishwarshafin** [comment] 2019-07-23 15:53
can you please try this:
```bash
sudo docker run -v /media/datarun2/helendata:/data kishwars/helen:0.0.1.cpu call_consensus.py \
-i images/ \
-b 64 \
-m models/r941_flip235_v001.pkl \
-o out/ \
-w 16 \
-t 1
```

**Comment by kishwarshafin** [comment] 2019-07-23 15:54
also, could you please let me know the output of `sudo docker images`

**Comment by lstxmu** [comment] 2019-07-23 15:55
@kishwarshafin  i wil try with your new suggestion. just give me a few minutes.

**Comment by lstxmu** [comment] 2019-07-23 16:07
@kishwarshafin   Follow your new  suggestion command .    I can see one hdf file was created with 96b size.  But  5 mins past, nothing changed.  with top comand, the status of python3 was "D" .  I had a screenshot for you. 
![Selection_097](https://user-images.githubusercontent.com/46129804/61728045-fb12cb00-ada6-11e9-8c07-01516ad4089c.png)

**Comment by lstxmu** [comment] 2019-07-23 16:09
sudo docker image ls                                                                            
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kishwars/helen      0.0.1.cpu           19b8257ea75a        2 days ago          1.2GB

**Comment by kishwarshafin** [comment] 2019-07-23 16:10
@lstxmu , the python3 with `D` is not the docker image. Do you see any output from the run? Do you see any output if you run this:
`sudo docker run -v /media/datarun2/helendata:/data kishwars/helen:0.0.1.cpu call_consensus.py -h`

**Comment by lstxmu** [comment] 2019-07-23 16:12
yes i can see the output.
![Selection_098](https://user-images.githubusercontent.com/46129804/61728396-b76c9100-ada7-11e9-948b-6c32ebc8bfd7.png)

**Comment by kishwarshafin** [comment] 2019-07-23 16:13
Do you see any output when you run this?
`sudo docker run -v /media/datarun2/helendata:/data kishwars/helen:0.0.1.cpu call_consensus.py -i images/ -b 64 -m models/r941_flip235_v001.pkl -o out/ -w 0 -t 1`

**Comment by lstxmu** [comment] 2019-07-23 16:15
nope,  just the comand stay there, and nothing show up after 10 mins . you can see my screenshot with time.
![Selection_099](https://user-images.githubusercontent.com/46129804/61728598-22b66300-ada8-11e9-9a91-4d70616a88d8.png)

**Comment by lstxmu** [comment] 2019-07-23 16:19
![Selection_100](https://user-images.githubusercontent.com/46129804/61728890-a8d2a980-ada8-11e9-98af-731637da99d3.png)
The screenshot at 00:19

**Comment by kishwarshafin** [comment] 2019-07-23 16:23
OK, two last things, if we can't find a resolution with these two then I would put the `help needed` in this issue. 
1) Can you perform a `reboot` and then do a docker pull again? I know this is very unlikely to work but the world of compute craziness reboots sometimes work.  
```
sudo docker pull kishwars/helen:0.0.1.cpu
```

2) If you are able to `reboot`. Please run the command in one line without using `\` line-breakers like:
```
sudo docker run -v /media/datarun2/helendata:/data kishwars/helen:0.0.1.cpu call_consensus.py -i images/ -b 64 -m models/r941_flip235_v001.pkl -o out/ -w 16 -t 1
```
Your previous comments have outputs like "Loading Data" and stuff, the program should go to that point nonetheless. And finally can you please give a screenshot of this:
```
cd /media/datarun2/helendata/images/
ls -a
```

**Comment by lstxmu** [comment] 2019-07-23 16:27
cd /media/datarun2/helendata/images/
ls -a
![Selection_102](https://user-images.githubusercontent.com/46129804/61729424-c2c0bc00-ada9-11e9-9ec9-58f862c6492e.png)

**Comment by lstxmu** [comment] 2019-07-23 16:27
![image](https://user-images.githubusercontent.com/46129804/61729465-dc620380-ada9-11e9-86bf-0b126df9d981.png)

**Comment by lstxmu** [comment] 2019-07-23 16:29
# root @ debian in /media/datarun2/helendata/images [0:25:47] 
$ ls -a  
./                     scmar.T100.h5  scmar.T114.h5  scmar.T128.h5  scmar.T141.h5  scmar.T26.h5  scmar.T41.h5  scmar.T56.h5  scmar.T71.h5  scmar.T86.h5
../                    scmar.T101.h5  scmar.T115.h5  scmar.T129.h5  scmar.T142.h5  scmar.T27.h5  scmar.T42.h5  scmar.T57.h5  scmar.T72.h5  scmar.T87.h5
po.txt                 scmar.T102.h5  scmar.T116.h5  scmar.T12.h5   scmar.T143.h5  scmar.T28.h5  scmar.T43.h5  scmar.T58.h5  scmar.T73.h5  scmar.T88.h5
r941_flip235_v001.pkl  scmar.T103.h5  scmar.T117.h5  scmar.T130.h5  scmar.T14.h5   scmar.T29.h5  scmar.T44.h5  scmar.T59.h5  scmar.T74.h5  scmar.T89.h5
scmar.fa               scmar.T104.h5  scmar.T118.h5  scmar.T131.h5  scmar.T15.h5   scmar.T30.h5  scmar.T45.h5  scmar.T60.h5  scmar.T75.h5  scmar.T90.h5
scmar.T00.h5           scmar.T105.h5  scmar.T119.h5  scmar.T132.h5  scmar.T16.h5   scmar.T31.h5  scmar.T46.h5  scmar.T61.h5  scmar.T76.h5  scmar.T91.h5
scmar.T01.h5           scmar.T106.h5  scmar.T11.h5   scmar.T133.h5  scmar.T17.h5   scmar.T32.h5  scmar.T47.h5  scmar.T62.h5  scmar.T77.h5  scmar.T92.h5
scmar.T02.h5           scmar.T107.h5  scmar.T120.h5  scmar.T134.h5  scmar.T18.h5   scmar.T33.h5  scmar.T48.h5  scmar.T63.h5  scmar.T78.h5  scmar.T93.h5
scmar.T03.h5           scmar.T108.h5  scmar.T121.h5  scmar.T135.h5  scmar.T19.h5   scmar.T34.h5  scmar.T49.h5  scmar.T64.h5  scmar.T79.h5  scmar.T94.h5
scmar.T04.h5           scmar.T109.h5  scmar.T122.h5  scmar.T136.h5  scmar.T20.h5   scmar.T35.h5  scmar.T50.h5  scmar.T65.h5  scmar.T80.h5  scmar.T95.h5
scmar.T05.h5           scmar.T10.h5   scmar.T123.h5  scmar.T137.h5  scmar.T21.h5   scmar.T36.h5  scmar.T51.h5  scmar.T66.h5  scmar.T81.h5  scmar.T96.h5
scmar.T06.h5           scmar.T110.h5  scmar.T124.h5  scmar.T138.h5  scmar.T22.h5   scmar.T37.h5  scmar.T52.h5  scmar.T67.h5  scmar.T82.h5  scmar.T97.h5
scmar.T07.h5           scmar.T111.h5  scmar.T125.h5  scmar.T139.h5  scmar.T23.h5   scmar.T38.h5  scmar.T53.h5  scmar.T68.h5  scmar.T83.h5  scmar.T98.h5
scmar.T08.h5           scmar.T112.h5  scmar.T126.h5  scmar.T13.h5   scmar.T24.h5   scmar.T39.h5  scmar.T54.h5  scmar.T69.h5  scmar.T84.h5  scmar.T99.h5
scmar.T09.h5           scmar.T113.h5  scmar.T127.h5  scmar.T140.h5  scmar.T25.h5   scmar.T40.h5  scmar.T55.h5  scmar.T70.h5  scmar.T85.h5

# root @ debian in /media/datarun2/helendata/images [0:25:52] 
$ reboot                                  
Connection to 192.168.1.102 closed by remote host.
Connection to 192.168.1.102 closed.

**Comment by kishwarshafin** [comment] 2019-07-23 16:30
@lstxmu , when it boots up please run:
`sudo service docker restart`

**Comment by lstxmu** [comment] 2019-07-23 16:42
eaebce5459f2: Pull complete 
Digest: sha256:9e7c84d432832ebd18e0326e1ae14a79a0ff1c6b6b879c68c1bc7d957a62bbe6
Status: Downloaded newer image for kishwars/helen:0.0.1.cpu

# root @ debian in /media/datarun2/helendata/images [0:37:55] 
$ sudo service docker restart

# root @ debian in /media/datarun2/helendata/out [0:38:37] 
$ sudo docker run -v /media/datarun2/helendata:/data kishwars/helen:0.0.1.cpu call_consensus.py -i images/ -b 64 -m models/r941_flip235_v001.pkl -o out/ -w 16 -t 1

I  had try reboot , re pull the docker image  and restart the docker service.
then re run the comand you gave.   but  nothing had changed,  it happen as previous described.
I'm sorry.

**Comment by kishwarshafin** [comment] 2019-07-23 16:50
Ok, no problem, I'll stick the help wanted tag here. If you can, please try this in a ubuntu machine, that should give you no problem. I am not sure why this is happening.

**Comment by lstxmu** [comment] 2019-07-23 16:55
@kishwarshafin  OK, i will rent a vps machine with ubuntu os to fininsh this job.  And one more question: have you test Shasta to assembly the Pacbio sequecne data?  does it perform better than wtdbg2 or other long reads assembly program ?

**Comment by kishwarshafin** [comment] 2019-07-23 16:57
@lstxmu , we haven't tried any PacBio data so far. Our group specializes in `Nanopore` but we have plans to explore `PacBio` data too in the near future. So, I am not exactly sure which assembler is better for `PacBio`.

**Comment by lstxmu** [comment] 2019-07-23 17:04
@kishwarshafin  OK, maybe i will try to do some test with Pacbio data .  I'll keep in touch with you.  I had follow you on twitter. @kishwarshafin ‏

**Comment by kishwarshafin** [comment] 2019-08-18 18:03
Hello, I am closing this issue for now as there hasn't been any activity in a while. Please feel free to reopen if you need help. However, I can confirm that we have at least two Debian users who successfully ran MP-HELEN in their system. Please let us know if you need any help.

**Closed as completed by kishwarshafin** 2019-08-18 18:03 UTC
Labels: help wanted
